defmodule Dota.Ability do
  @abilities %{
    5003 => %{"id" => 5003, "hero_id"=>1, "name"=>"antimage_mana_break", "localized_name"=>"Mana Break"},
    5004 => %{"id" => 5004, "hero_id"=>1, "name"=>"antimage_blink", "localized_name"=>"Blink"},
    5005 => %{"id" => 5005, "hero_id"=>1, "name"=>"antimage_spell_shield", "localized_name"=>"Spell Shield"},
    5006 => %{"id" => 5006, "hero_id"=>1, "name"=>"antimage_mana_void", "localized_name"=>"Mana Void"},
    5007 => %{"id" => 5007, "hero_id"=>2, "name"=>"axe_berserkers_call", "localized_name"=>"Berserker's Call"},
    5008 => %{"id" => 5008, "hero_id"=>2, "name"=>"axe_battle_hunger", "localized_name"=>"Battle Hunger"},
    5009 => %{"id" => 5009, "hero_id"=>2, "name"=>"axe_counter_helix", "localized_name"=>"Counter Helix"},
    5010 => %{"id" => 5010, "hero_id"=>2, "name"=>"axe_culling_blade", "localized_name"=>"Culling Blade"},
    5012 => %{"id" => 5012, "hero_id"=>3, "name"=>"bane_enfeeble", "localized_name"=>"Enfeeble"},
    5011 => %{"id" => 5011, "hero_id"=>3, "name"=>"bane_brain_sap", "localized_name"=>"Brain Sap"},
    5013 => %{"id" => 5013, "hero_id"=>3, "name"=>"bane_fiends_grip", "localized_name"=>"Fiend's Grip"},
    5014 => %{"id" => 5014, "hero_id"=>3, "name"=>"bane_nightmare", "localized_name"=>"Nightmare"},
    5523 => %{"id" => 5523, "hero_id"=>3, "name"=>"bane_nightmare_end", "localized_name"=>"Nightmare End"},
    5015 => %{"id" => 5015, "hero_id"=>4, "name"=>"bloodseeker_bloodrage", "localized_name"=>"Bloodrage"},
    5016 => %{"id" => 5016, "hero_id"=>4, "name"=>"bloodseeker_blood_bath", "localized_name"=>"Blood Bath"},
    5017 => %{"id" => 5017, "hero_id"=>4, "name"=>"bloodseeker_thirst", "localized_name"=>"Thirst"},
    5018 => %{"id" => 5018, "hero_id"=>4, "name"=>"bloodseeker_rupture", "localized_name"=>"Rupture"},
    5019 => %{"id" => 5019, "hero_id"=>6, "name"=>"drow_ranger_frost_arrows", "localized_name"=>"Frost Arrows"},
    5632 => %{"id" => 5632, "hero_id"=>6, "name"=>"drow_ranger_wave_of_silence", "localized_name"=>"Gust"},
    5021 => %{"id" => 5021, "hero_id"=>6, "name"=>"drow_ranger_trueshot", "localized_name"=>"Precision Aura"},
    5022 => %{"id" => 5022, "hero_id"=>6, "name"=>"drow_ranger_marksmanship", "localized_name"=>"Marksmanship"},
    5023 => %{"id" => 5023, "hero_id"=>7, "name"=>"earthshaker_fissure", "localized_name"=>"Fissure"},
    5024 => %{"id" => 5024, "hero_id"=>7, "name"=>"earthshaker_enchant_totem", "localized_name"=>"Enchant Totem"},
    5025 => %{"id" => 5025, "hero_id"=>7, "name"=>"earthshaker_aftershock", "localized_name"=>"Aftershock"},
    5026 => %{"id" => 5026, "hero_id"=>7, "name"=>"earthshaker_echo_slam", "localized_name"=>"Echo Slam"},
    5027 => %{"id" => 5027, "hero_id"=>8, "name"=>"juggernaut_blade_dance", "localized_name"=>"Blade Dance"},
    5028 => %{"id" => 5028, "hero_id"=>8, "name"=>"juggernaut_blade_fury", "localized_name"=>"Blade Fury"},
    5029 => %{"id" => 5029, "hero_id"=>8, "name"=>"juggernaut_healing_ward", "localized_name"=>"Healing Ward"},
    5030 => %{"id" => 5030, "hero_id"=>8, "name"=>"juggernaut_omni_slash", "localized_name"=>"Omnislash"},
    5031 => %{"id" => 5031, "hero_id"=>23, "name"=>"kunkka_torrent", "localized_name"=>"Torrent"},
    5032 => %{"id" => 5032, "hero_id"=>23, "name"=>"kunkka_tidebringer", "localized_name"=>"Tidebringer"},
    5033 => %{"id" => 5033, "hero_id"=>23, "name"=>"kunkka_x_marks_the_spot", "localized_name"=>"X Marks the Spot"},
    5034 => %{"id" => 5034, "hero_id"=>23, "name"=>"kunkka_return", "localized_name"=>"Return"},
    5035 => %{"id" => 5035, "hero_id"=>23, "name"=>"kunkka_ghostship", "localized_name"=>"Ghostship"},
    5040 => %{"id" => 5040, "hero_id"=>25, "name"=>"lina_dragon_slave", "localized_name"=>"Dragon Slave"},
    5041 => %{"id" => 5041, "hero_id"=>25, "name"=>"lina_light_strike_array", "localized_name"=>"Light Strike Array"},
    5042 => %{"id" => 5042, "hero_id"=>25, "name"=>"lina_fiery_soul", "localized_name"=>"Fiery Soul"},
    5043 => %{"id" => 5043, "hero_id"=>25, "name"=>"lina_laguna_blade", "localized_name"=>"Laguna Blade"},
    5044 => %{"id" => 5044, "hero_id"=>26, "name"=>"lion_impale", "localized_name"=>"Earth Spike"},
    5045 => %{"id" => 5045, "hero_id"=>26, "name"=>"lion_voodoo", "localized_name"=>"Hex"},
    5046 => %{"id" => 5046, "hero_id"=>26, "name"=>"lion_mana_drain", "localized_name"=>"Mana Drain"},
    5047 => %{"id" => 5047, "hero_id"=>26, "name"=>"lion_finger_of_death", "localized_name"=>"Finger of Death"},
    5048 => %{"id" => 5048, "hero_id"=>9, "name"=>"mirana_arrow", "localized_name"=>"Sacred Arrow"},
    5049 => %{"id" => 5049, "hero_id"=>9, "name"=>"mirana_invis", "localized_name"=>"Moonlight Shadow"},
    5050 => %{"id" => 5050, "hero_id"=>9, "name"=>"mirana_leap", "localized_name"=>"Leap"},
    5051 => %{"id" => 5051, "hero_id"=>9, "name"=>"mirana_starfall", "localized_name"=>"Starstorm"},
    5052 => %{"id" => 5052, "hero_id"=>10, "name"=>"morphling_waveform", "localized_name"=>"Waveform"},
    5053 => %{"id" => 5053, "hero_id"=>10, "name"=>"morphling_adaptive_strike", "localized_name"=>"Adaptive Strike"},
    5055 => %{"id" => 5055, "hero_id"=>10, "name"=>"morphling_morph_agi", "localized_name"=>"Morph (Agility Gain)"},
    5056 => %{"id" => 5056, "hero_id"=>10, "name"=>"morphling_morph_str", "localized_name"=>"Morph (Strength Gain)"},
    5057 => %{"id" => 5057, "hero_id"=>10, "name"=>"morphling_replicate", "localized_name"=>"Replicate"},
    5058 => %{"id" => 5058, "hero_id"=>10, "name"=>"morphling_morph_replicate", "localized_name"=>"Morph Replicate"},
    5059 => %{"id" => 5059, "hero_id"=>11, "name"=>"nevermore_shadowraze1", "localized_name"=>"Shadowraze"},
    5060 => %{"id" => 5060, "hero_id"=>11, "name"=>"nevermore_shadowraze2", "localized_name"=>"Shadowraze"},
    5061 => %{"id" => 5061, "hero_id"=>11, "name"=>"nevermore_shadowraze3", "localized_name"=>"Shadowraze"},
    5062 => %{"id" => 5062, "hero_id"=>11, "name"=>"nevermore_necromastery", "localized_name"=>"Necromastery"},
    5063 => %{"id" => 5063, "hero_id"=>11, "name"=>"nevermore_dark_lord", "localized_name"=>"Presence of the Dark Lord"},
    5064 => %{"id" => 5064, "hero_id"=>11, "name"=>"nevermore_requiem", "localized_name"=>"Requiem of Souls"},
    5065 => %{"id" => 5065, "hero_id"=>12, "name"=>"phantom_lancer_spirit_lance", "localized_name"=>"Spirit Lance"},
    5066 => %{"id" => 5066, "hero_id"=>12, "name"=>"phantom_lancer_doppelwalk", "localized_name"=>"Doppelwalk"},
    5067 => %{"id" => 5067, "hero_id"=>12, "name"=>"phantom_lancer_juxtapose", "localized_name"=>"Juxtapose"},
    5068 => %{"id" => 5068, "hero_id"=>12, "name"=>"phantom_lancer_phantom_edge", "localized_name"=>"Phantom Edge"},
    5069 => %{"id" => 5069, "hero_id"=>13, "name"=>"puck_illusory_orb", "localized_name"=>"Illusory Orb"},
    5070 => %{"id" => 5070, "hero_id"=>13, "name"=>"puck_ethereal_jaunt", "localized_name"=>"Ethereal Jaunt"},
    5071 => %{"id" => 5071, "hero_id"=>13, "name"=>"puck_waning_rift", "localized_name"=>"Waning Rift"},
    5072 => %{"id" => 5072, "hero_id"=>13, "name"=>"puck_phase_shift", "localized_name"=>"Phase Shift"},
    5073 => %{"id" => 5073, "hero_id"=>13, "name"=>"puck_dream_coil", "localized_name"=>"Dream Coil"},
    5074 => %{"id" => 5074, "hero_id"=>14, "name"=>"pudge_flesh_heap", "localized_name"=>"Flesh Heap"},
    5075 => %{"id" => 5075, "hero_id"=>14, "name"=>"pudge_meat_hook", "localized_name"=>"Meat Hook"},
    5076 => %{"id" => 5076, "hero_id"=>14, "name"=>"pudge_rot", "localized_name"=>"Rot"},
    5077 => %{"id" => 5077, "hero_id"=>14, "name"=>"pudge_dismember", "localized_name"=>"Dismember"},
    5078 => %{"id" => 5078, "hero_id"=>27, "name"=>"shadow_shaman_ether_shock", "localized_name"=>"Ether Shock"},
    5079 => %{"id" => 5079, "hero_id"=>27, "name"=>"shadow_shaman_voodoo", "localized_name"=>"Hex"},
    5080 => %{"id" => 5080, "hero_id"=>27, "name"=>"shadow_shaman_shackles", "localized_name"=>"Shackles"},
    5081 => %{"id" => 5081, "hero_id"=>27, "name"=>"shadow_shaman_mass_serpent_ward", "localized_name"=>"Mass Serpent Ward"},
    5082 => %{"id" => 5082, "hero_id"=>15, "name"=>"razor_plasma_field", "localized_name"=>"Plasma Field"},
    5083 => %{"id" => 5083, "hero_id"=>15, "name"=>"razor_static_link", "localized_name"=>"Static Link"},
    5084 => %{"id" => 5084, "hero_id"=>15, "name"=>"razor_unstable_current", "localized_name"=>"Unstable Current"},
    5085 => %{"id" => 5085, "hero_id"=>15, "name"=>"razor_eye_of_the_storm", "localized_name"=>"Eye of the Storm"},
    5086 => %{"id" => 5086, "hero_id"=>42, "name"=>"skeleton_king_hellfire_blast", "localized_name"=>"Wraithfire Blast"},
    5087 => %{"id" => 5087, "hero_id"=>42, "name"=>"skeleton_king_vampiric_aura", "localized_name"=>"Vampiric Aura"},
    5088 => %{"id" => 5088, "hero_id"=>42, "name"=>"skeleton_king_mortal_strike", "localized_name"=>"Mortal Strike"},
    5089 => %{"id" => 5089, "hero_id"=>42, "name"=>"skeleton_king_reincarnation", "localized_name"=>"Reincarnation"},
    5090 => %{"id" => 5090, "hero_id"=>43, "name"=>"death_prophet_carrion_swarm", "localized_name"=>"Crypt Swarm"},
    5091 => %{"id" => 5091, "hero_id"=>43, "name"=>"death_prophet_silence", "localized_name"=>"Silence"},
    5092 => %{"id" => 5092, "hero_id"=>43, "name"=>"death_prophet_witchcraft", "localized_name"=>"Witchcraft"},
    5093 => %{"id" => 5093, "hero_id"=>43, "name"=>"death_prophet_exorcism", "localized_name"=>"Exorcism"},
    5094 => %{"id" => 5094, "hero_id"=>18, "name"=>"sven_storm_bolt", "localized_name"=>"Storm Hammer"},
    5095 => %{"id" => 5095, "hero_id"=>18, "name"=>"sven_great_cleave", "localized_name"=>"Great Cleave"},
    5096 => %{"id" => 5096, "hero_id"=>18, "name"=>"sven_warcry", "localized_name"=>"Warcry"},
    5097 => %{"id" => 5097, "hero_id"=>18, "name"=>"sven_gods_strength", "localized_name"=>"God's Strength"},
    5098 => %{"id" => 5098, "hero_id"=>17, "name"=>"storm_spirit_static_remnant", "localized_name"=>"Static Remnant"},
    5099 => %{"id" => 5099, "hero_id"=>17, "name"=>"storm_spirit_electric_vortex", "localized_name"=>"Electric Vortex"},
    5100 => %{"id" => 5100, "hero_id"=>17, "name"=>"storm_spirit_overload", "localized_name"=>"Overload"},
    5101 => %{"id" => 5101, "hero_id"=>17, "name"=>"storm_spirit_ball_lightning", "localized_name"=>"Ball Lightning"},
    5102 => %{"id" => 5102, "hero_id"=>16, "name"=>"sandking_burrowstrike", "localized_name"=>"Burrowstrike"},
    5103 => %{"id" => 5103, "hero_id"=>16, "name"=>"sandking_sand_storm", "localized_name"=>"Sand Storm"},
    5104 => %{"id" => 5104, "hero_id"=>16, "name"=>"sandking_caustic_finale", "localized_name"=>"Caustic Finale"},
    5105 => %{"id" => 5105, "hero_id"=>16, "name"=>"sandking_epicenter", "localized_name"=>"Epicenter"},
    5106 => %{"id" => 5106, "hero_id"=>19, "name"=>"tiny_avalanche", "localized_name"=>"Avalanche"},
    5107 => %{"id" => 5107, "hero_id"=>19, "name"=>"tiny_toss", "localized_name"=>"Toss"},
    5108 => %{"id" => 5108, "hero_id"=>19, "name"=>"tiny_craggy_exterior", "localized_name"=>"Craggy Exterior"},
    5109 => %{"id" => 5109, "hero_id"=>19, "name"=>"tiny_grow", "localized_name"=>"Grow"},
    5110 => %{"id" => 5110, "hero_id"=>22, "name"=>"zuus_arc_lightning", "localized_name"=>"Arc Lightning"},
    5111 => %{"id" => 5111, "hero_id"=>22, "name"=>"zuus_lightning_bolt", "localized_name"=>"Lightning Bolt"},
    5112 => %{"id" => 5112, "hero_id"=>22, "name"=>"zuus_static_field", "localized_name"=>"Static Field"},
    5113 => %{"id" => 5113, "hero_id"=>22, "name"=>"zuus_thundergods_wrath", "localized_name"=>"Thundergod's Wrath"},
    5114 => %{"id" => 5114, "hero_id"=>28, "name"=>"slardar_sprint", "localized_name"=>"Sprint"},
    5115 => %{"id" => 5115, "hero_id"=>28, "name"=>"slardar_slithereen_crush", "localized_name"=>"Slithereen Crush"},
    5116 => %{"id" => 5116, "hero_id"=>28, "name"=>"slardar_bash", "localized_name"=>"Bash"},
    5117 => %{"id" => 5117, "hero_id"=>28, "name"=>"slardar_amplify_damage", "localized_name"=>"Amplify Damage"},
    5118 => %{"id" => 5118, "hero_id"=>29, "name"=>"tidehunter_gush", "localized_name"=>"Gush"},
    5119 => %{"id" => 5119, "hero_id"=>29, "name"=>"tidehunter_kraken_shell", "localized_name"=>"Kraken Shell"},
    5120 => %{"id" => 5120, "hero_id"=>29, "name"=>"tidehunter_anchor_smash", "localized_name"=>"Anchor Smash"},
    5121 => %{"id" => 5121, "hero_id"=>29, "name"=>"tidehunter_ravage", "localized_name"=>"Ravage"},
    5122 => %{"id" => 5122, "hero_id"=>20, "name"=>"vengefulspirit_magic_missile", "localized_name"=>"Magic Missile"},
    5123 => %{"id" => 5123, "hero_id"=>20, "name"=>"vengefulspirit_command_aura", "localized_name"=>"Vengeance Aura"},
    5124 => %{"id" => 5124, "hero_id"=>20, "name"=>"vengefulspirit_wave_of_terror", "localized_name"=>"Wave of Terror"},
    5125 => %{"id" => 5125, "hero_id"=>20, "name"=>"vengefulspirit_nether_swap", "localized_name"=>"Nether Swap"},
    5126 => %{"id" => 5126, "hero_id"=>5, "name"=>"crystal_maiden_crystal_nova", "localized_name"=>"Crystal Nova"},
    5127 => %{"id" => 5127, "hero_id"=>5, "name"=>"crystal_maiden_frostbite", "localized_name"=>"Frostbite"},
    5128 => %{"id" => 5128, "hero_id"=>5, "name"=>"crystal_maiden_brilliance_aura", "localized_name"=>"Arcane Aura"},
    5129 => %{"id" => 5129, "hero_id"=>5, "name"=>"crystal_maiden_freezing_field", "localized_name"=>"Freezing Field"},
    5130 => %{"id" => 5130, "hero_id"=>21, "name"=>"windrunner_shackleshot", "localized_name"=>"Shackleshot"},
    5131 => %{"id" => 5131, "hero_id"=>21, "name"=>"windrunner_powershot", "localized_name"=>"Powershot"},
    5132 => %{"id" => 5132, "hero_id"=>21, "name"=>"windrunner_windrun", "localized_name"=>"Windrun"},
    5133 => %{"id" => 5133, "hero_id"=>21, "name"=>"windrunner_focusfire", "localized_name"=>"Focus Fire"},
    5134 => %{"id" => 5134, "hero_id"=>31, "name"=>"lich_frost_nova", "localized_name"=>"Frost Blast"},
    5135 => %{"id" => 5135, "hero_id"=>31, "name"=>"lich_frost_armor", "localized_name"=>"Ice Armor"},
    5136 => %{"id" => 5136, "hero_id"=>31, "name"=>"lich_dark_ritual", "localized_name"=>"Sacrifice"},
    5137 => %{"id" => 5137, "hero_id"=>31, "name"=>"lich_chain_frost", "localized_name"=>"Chain Frost"},
    5138 => %{"id" => 5138, "hero_id"=>30, "name"=>"witch_doctor_paralyzing_cask", "localized_name"=>"Paralyzing Cask"},
    5139 => %{"id" => 5139, "hero_id"=>30, "name"=>"witch_doctor_voodoo_restoration", "localized_name"=>"Voodoo Restoration"},
    5140 => %{"id" => 5140, "hero_id"=>30, "name"=>"witch_doctor_maledict", "localized_name"=>"Maledict"},
    5141 => %{"id" => 5141, "hero_id"=>30, "name"=>"witch_doctor_death_ward", "localized_name"=>"Death Ward"},
    5142 => %{"id" => 5142, "hero_id"=>32, "name"=>"riki_smoke_screen", "localized_name"=>"Smoke Screen"},
    5143 => %{"id" => 5143, "hero_id"=>32, "name"=>"riki_blink_strike", "localized_name"=>"Blink Strike"},
    5144 => %{"id" => 5144, "hero_id"=>32, "name"=>"riki_backstab", "localized_name"=>"Backstab"},
    5145 => %{"id" => 5145, "hero_id"=>32, "name"=>"riki_permanent_invisibility", "localized_name"=>"Permanent Invisibility"},
    5146 => %{"id" => 5146, "hero_id"=>33, "name"=>"enigma_malefice", "localized_name"=>"Malefice"},
    5147 => %{"id" => 5147, "hero_id"=>33, "name"=>"enigma_demonic_conversion", "localized_name"=>"Demonic Conversion"},
    5148 => %{"id" => 5148, "hero_id"=>33, "name"=>"enigma_midnight_pulse", "localized_name"=>"Midnight Pulse"},
    5149 => %{"id" => 5149, "hero_id"=>33, "name"=>"enigma_black_hole", "localized_name"=>"Black Hole"},
    5150 => %{"id" => 5150, "hero_id"=>34, "name"=>"tinker_laser", "localized_name"=>"Laser"},
    5151 => %{"id" => 5151, "hero_id"=>34, "name"=>"tinker_heat_seeking_missile", "localized_name"=>"Heat-Seeking Missile"},
    5152 => %{"id" => 5152, "hero_id"=>34, "name"=>"tinker_march_of_the_machines", "localized_name"=>"March of the Machines"},
    5153 => %{"id" => 5153, "hero_id"=>34, "name"=>"tinker_rearm", "localized_name"=>"Rearm"},
    5154 => %{"id" => 5154, "hero_id"=>35, "name"=>"sniper_shrapnel", "localized_name"=>"Shrapnel"},
    5155 => %{"id" => 5155, "hero_id"=>35, "name"=>"sniper_headshot", "localized_name"=>"Headshot"},
    5156 => %{"id" => 5156, "hero_id"=>35, "name"=>"sniper_take_aim", "localized_name"=>"Take Aim"},
    5157 => %{"id" => 5157, "hero_id"=>35, "name"=>"sniper_assassinate", "localized_name"=>"Assassinate"},
    5158 => %{"id" => 5158, "hero_id"=>36, "name"=>"necrolyte_death_pulse", "localized_name"=>"Death Pulse"},
    5159 => %{"id" => 5159, "hero_id"=>36, "name"=>"necrolyte_heartstopper_aura", "localized_name"=>"Heartstopper Aura"},
    5160 => %{"id" => 5160, "hero_id"=>36, "name"=>"necrolyte_sadist", "localized_name"=>"Sadist"},
    5161 => %{"id" => 5161, "hero_id"=>36, "name"=>"necrolyte_reapers_scythe", "localized_name"=>"Reaper's Scythe"},
    5162 => %{"id" => 5162, "hero_id"=>37, "name"=>"warlock_fatal_bonds", "localized_name"=>"Fatal Bonds"},
    5163 => %{"id" => 5163, "hero_id"=>37, "name"=>"warlock_shadow_word", "localized_name"=>"Shadow Word"},
    5164 => %{"id" => 5164, "hero_id"=>37, "name"=>"warlock_upheaval", "localized_name"=>"Upheaval"},
    5165 => %{"id" => 5165, "hero_id"=>37, "name"=>"warlock_rain_of_chaos", "localized_name"=>"Chaotic Offering"},
    5168 => %{"id" => 5168, "hero_id"=>38, "name"=>"beastmaster_wild_axes", "localized_name"=>"Wild Axes"},
    5169 => %{"id" => 5169, "hero_id"=>38, "name"=>"beastmaster_call_of_the_wild", "localized_name"=>"Call of the Wild"},
    5580 => %{"id" => 5580, "hero_id"=>38, "name"=>"beastmaster_call_of_the_wild_boar", "localized_name"=>"Call of the Wild"},
    5172 => %{"id" => 5172, "hero_id"=>38, "name"=>"beastmaster_inner_beast", "localized_name"=>"Inner Beast"},
    5177 => %{"id" => 5177, "hero_id"=>38, "name"=>"beastmaster_primal_roar", "localized_name"=>"Primal Roar"},
    5173 => %{"id" => 5173, "hero_id"=>39, "name"=>"queenofpain_shadow_strike", "localized_name"=>"Shadow Strike"},
    5174 => %{"id" => 5174, "hero_id"=>39, "name"=>"queenofpain_blink", "localized_name"=>"Blink"},
    5175 => %{"id" => 5175, "hero_id"=>39, "name"=>"queenofpain_scream_of_pain", "localized_name"=>"Scream Of Pain"},
    5176 => %{"id" => 5176, "hero_id"=>39, "name"=>"queenofpain_sonic_wave", "localized_name"=>"Sonic Wave"},
    5178 => %{"id" => 5178, "hero_id"=>40, "name"=>"venomancer_venomous_gale", "localized_name"=>"Venomous Gale"},
    5179 => %{"id" => 5179, "hero_id"=>40, "name"=>"venomancer_poison_sting", "localized_name"=>"Poison Sting"},
    5180 => %{"id" => 5180, "hero_id"=>40, "name"=>"venomancer_plague_ward", "localized_name"=>"Plague Ward"},
    5181 => %{"id" => 5181, "hero_id"=>40, "name"=>"venomancer_poison_nova", "localized_name"=>"Poison Nova"},
    5182 => %{"id" => 5182, "hero_id"=>41, "name"=>"faceless_void_time_walk", "localized_name"=>"Time Walk"},
    5183 => %{"id" => 5183, "hero_id"=>41, "name"=>"faceless_void_backtrack", "localized_name"=>"Backtrack"},
    5184 => %{"id" => 5184, "hero_id"=>41, "name"=>"faceless_void_time_lock", "localized_name"=>"Time Lock"},
    5185 => %{"id" => 5185, "hero_id"=>41, "name"=>"faceless_void_chronosphere", "localized_name"=>"Chronosphere"},
    5186 => %{"id" => 5186, "hero_id"=>45, "name"=>"pugna_nether_blast", "localized_name"=>"Nether Blast"},
    5187 => %{"id" => 5187, "hero_id"=>45, "name"=>"pugna_decrepify", "localized_name"=>"Decrepify"},
    5188 => %{"id" => 5188, "hero_id"=>45, "name"=>"pugna_nether_ward", "localized_name"=>"Nether Ward"},
    5189 => %{"id" => 5189, "hero_id"=>45, "name"=>"pugna_life_drain", "localized_name"=>"Life Drain"},
    5190 => %{"id" => 5190, "hero_id"=>44, "name"=>"phantom_assassin_stifling_dagger", "localized_name"=>"Stifling Dagger"},
    5191 => %{"id" => 5191, "hero_id"=>44, "name"=>"phantom_assassin_phantom_strike", "localized_name"=>"Phantom Strike"},
    5192 => %{"id" => 5192, "hero_id"=>44, "name"=>"phantom_assassin_blur", "localized_name"=>"Blur"},
    5193 => %{"id" => 5193, "hero_id"=>44, "name"=>"phantom_assassin_coup_de_grace", "localized_name"=>"Coup de Grace"},
    5194 => %{"id" => 5194, "hero_id"=>46, "name"=>"templar_assassin_refraction", "localized_name"=>"Refraction"},
    5195 => %{"id" => 5195, "hero_id"=>46, "name"=>"templar_assassin_meld", "localized_name"=>"Meld"},
    5196 => %{"id" => 5196, "hero_id"=>46, "name"=>"templar_assassin_psi_blades", "localized_name"=>"Psi Blades"},
    5197 => %{"id" => 5197, "hero_id"=>46, "name"=>"templar_assassin_psionic_trap", "localized_name"=>"Psionic Trap"},
    5198 => %{"id" => 5198, "hero_id"=>46, "name"=>"templar_assassin_trap", "localized_name"=>"Trap"},
    5218 => %{"id" => 5218, "hero_id"=>47, "name"=>"viper_poison_attack", "localized_name"=>"Poison Attack"},
    5219 => %{"id" => 5219, "hero_id"=>47, "name"=>"viper_nethertoxin", "localized_name"=>"Nethertoxin"},
    5220 => %{"id" => 5220, "hero_id"=>47, "name"=>"viper_corrosive_skin", "localized_name"=>"Corrosive Skin"},
    5221 => %{"id" => 5221, "hero_id"=>47, "name"=>"viper_viper_strike", "localized_name"=>"Viper Strike"},
    5222 => %{"id" => 5222, "hero_id"=>48, "name"=>"luna_lucent_beam", "localized_name"=>"Lucent Beam"},
    5223 => %{"id" => 5223, "hero_id"=>48, "name"=>"luna_moon_glaive", "localized_name"=>"Moon Glaive"},
    5224 => %{"id" => 5224, "hero_id"=>48, "name"=>"luna_lunar_blessing", "localized_name"=>"Lunar Blessing"},
    5225 => %{"id" => 5225, "hero_id"=>48, "name"=>"luna_eclipse", "localized_name"=>"Eclipse"},
    5226 => %{"id" => 5226, "hero_id"=>49, "name"=>"dragon_knight_breathe_fire", "localized_name"=>"Breathe Fire"},
    5227 => %{"id" => 5227, "hero_id"=>49, "name"=>"dragon_knight_dragon_tail", "localized_name"=>"Dragon Tail"},
    5228 => %{"id" => 5228, "hero_id"=>49, "name"=>"dragon_knight_dragon_blood", "localized_name"=>"Dragon Blood"},
    5229 => %{"id" => 5229, "hero_id"=>49, "name"=>"dragon_knight_elder_dragon_form", "localized_name"=>"Elder Dragon Form"},
    5233 => %{"id" => 5233, "hero_id"=>50, "name"=>"dazzle_poison_touch", "localized_name"=>"Poison Touch"},
    5234 => %{"id" => 5234, "hero_id"=>50, "name"=>"dazzle_shallow_grave", "localized_name"=>"Shallow Grave"},
    5235 => %{"id" => 5235, "hero_id"=>50, "name"=>"dazzle_shadow_wave", "localized_name"=>"Shadow Wave"},
    5236 => %{"id" => 5236, "hero_id"=>50, "name"=>"dazzle_weave", "localized_name"=>"Weave"},
    5237 => %{"id" => 5237, "hero_id"=>51, "name"=>"rattletrap_battery_assault", "localized_name"=>"Battery Assault"},
    5238 => %{"id" => 5238, "hero_id"=>51, "name"=>"rattletrap_power_cogs", "localized_name"=>"Power Cogs"},
    5239 => %{"id" => 5239, "hero_id"=>51, "name"=>"rattletrap_rocket_flare", "localized_name"=>"Rocket Flare"},
    5240 => %{"id" => 5240, "hero_id"=>51, "name"=>"rattletrap_hookshot", "localized_name"=>"Hookshot"},
    5241 => %{"id" => 5241, "hero_id"=>52, "name"=>"leshrac_split_earth", "localized_name"=>"Split Earth"},
    5242 => %{"id" => 5242, "hero_id"=>52, "name"=>"leshrac_diabolic_edict", "localized_name"=>"Diabolic Edict"},
    5243 => %{"id" => 5243, "hero_id"=>52, "name"=>"leshrac_lightning_storm", "localized_name"=>"Lightning Storm"},
    5244 => %{"id" => 5244, "hero_id"=>52, "name"=>"leshrac_pulse_nova", "localized_name"=>"Pulse Nova"},
    5245 => %{"id" => 5245, "hero_id"=>53, "name"=>"furion_sprout", "localized_name"=>"Sprout"},
    5246 => %{"id" => 5246, "hero_id"=>53, "name"=>"furion_teleportation", "localized_name"=>"Teleportation"},
    5247 => %{"id" => 5247, "hero_id"=>53, "name"=>"furion_force_of_nature", "localized_name"=>"Nature's Call"},
    5248 => %{"id" => 5248, "hero_id"=>53, "name"=>"furion_wrath_of_nature", "localized_name"=>"Wrath of Nature"},
    5249 => %{"id" => 5249, "hero_id"=>54, "name"=>"life_stealer_rage", "localized_name"=>"Rage"},
    5250 => %{"id" => 5250, "hero_id"=>54, "name"=>"life_stealer_feast", "localized_name"=>"Feast"},
    5251 => %{"id" => 5251, "hero_id"=>54, "name"=>"life_stealer_open_wounds", "localized_name"=>"Open Wounds"},
    5252 => %{"id" => 5252, "hero_id"=>54, "name"=>"life_stealer_infest", "localized_name"=>"Infest"},
    5253 => %{"id" => 5253, "hero_id"=>54, "name"=>"life_stealer_consume", "localized_name"=>"Consume"},
    5255 => %{"id" => 5255, "hero_id"=>55, "name"=>"dark_seer_vacuum", "localized_name"=>"Vacuum"},
    5256 => %{"id" => 5256, "hero_id"=>55, "name"=>"dark_seer_ion_shell", "localized_name"=>"Ion Shell"},
    5257 => %{"id" => 5257, "hero_id"=>55, "name"=>"dark_seer_surge", "localized_name"=>"Surge"},
    5258 => %{"id" => 5258, "hero_id"=>55, "name"=>"dark_seer_wall_of_replica", "localized_name"=>"Wall of Replica"},
    5259 => %{"id" => 5259, "hero_id"=>56, "name"=>"clinkz_strafe", "localized_name"=>"Strafe"},
    5260 => %{"id" => 5260, "hero_id"=>56, "name"=>"clinkz_searing_arrows", "localized_name"=>"Searing Arrows"},
    5261 => %{"id" => 5261, "hero_id"=>56, "name"=>"clinkz_wind_walk", "localized_name"=>"Skeleton Walk"},
    5262 => %{"id" => 5262, "hero_id"=>56, "name"=>"clinkz_death_pact", "localized_name"=>"Death Pact"},
    5263 => %{"id" => 5263, "hero_id"=>57, "name"=>"omniknight_purification", "localized_name"=>"Purification"},
    5264 => %{"id" => 5264, "hero_id"=>57, "name"=>"omniknight_repel", "localized_name"=>"Repel"},
    5265 => %{"id" => 5265, "hero_id"=>57, "name"=>"omniknight_degen_aura", "localized_name"=>"Degen Aura"},
    5266 => %{"id" => 5266, "hero_id"=>57, "name"=>"omniknight_guardian_angel", "localized_name"=>"Guardian Angel"},
    5267 => %{"id" => 5267, "hero_id"=>58, "name"=>"enchantress_untouchable", "localized_name"=>"Untouchable"},
    5268 => %{"id" => 5268, "hero_id"=>58, "name"=>"enchantress_enchant", "localized_name"=>"Enchant"},
    5269 => %{"id" => 5269, "hero_id"=>58, "name"=>"enchantress_natures_attendants", "localized_name"=>"Nature's Attendants"},
    5270 => %{"id" => 5270, "hero_id"=>58, "name"=>"enchantress_impetus", "localized_name"=>"Impetus"},
    5271 => %{"id" => 5271, "hero_id"=>59, "name"=>"huskar_inner_vitality", "localized_name"=>"Inner Vitality"},
    5272 => %{"id" => 5272, "hero_id"=>59, "name"=>"huskar_burning_spear", "localized_name"=>"Burning Spear"},
    5273 => %{"id" => 5273, "hero_id"=>59, "name"=>"huskar_berserkers_blood", "localized_name"=>"Berserker's Blood"},
    5274 => %{"id" => 5274, "hero_id"=>59, "name"=>"huskar_life_break", "localized_name"=>"Life Break"},
    5275 => %{"id" => 5275, "hero_id"=>60, "name"=>"night_stalker_void", "localized_name"=>"Void"},
    5276 => %{"id" => 5276, "hero_id"=>60, "name"=>"night_stalker_crippling_fear", "localized_name"=>"Crippling Fear"},
    5277 => %{"id" => 5277, "hero_id"=>60, "name"=>"night_stalker_hunter_in_the_night", "localized_name"=>"Hunter in the Night"},
    5278 => %{"id" => 5278, "hero_id"=>60, "name"=>"night_stalker_darkness", "localized_name"=>"Darkness"},
    5279 => %{"id" => 5279, "hero_id"=>61, "name"=>"broodmother_spawn_spiderlings", "localized_name"=>"Spawn Spiderlings"},
    5280 => %{"id" => 5280, "hero_id"=>61, "name"=>"broodmother_spin_web", "localized_name"=>"Spin Web"},
    5281 => %{"id" => 5281, "hero_id"=>61, "name"=>"broodmother_incapacitating_bite", "localized_name"=>"Incapacitating Bite"},
    5282 => %{"id" => 5282, "hero_id"=>61, "name"=>"broodmother_insatiable_hunger", "localized_name"=>"Insatiable Hunger"},
    5285 => %{"id" => 5285, "hero_id"=>62, "name"=>"bounty_hunter_shuriken_toss", "localized_name"=>"Shuriken Toss"},
    5286 => %{"id" => 5286, "hero_id"=>62, "name"=>"bounty_hunter_jinada", "localized_name"=>"Jinada"},
    5287 => %{"id" => 5287, "hero_id"=>62, "name"=>"bounty_hunter_wind_walk", "localized_name"=>"Shadow Walk"},
    5288 => %{"id" => 5288, "hero_id"=>62, "name"=>"bounty_hunter_track", "localized_name"=>"Track"},
    5289 => %{"id" => 5289, "hero_id"=>63, "name"=>"weaver_the_swarm", "localized_name"=>"The Swarm"},
    5290 => %{"id" => 5290, "hero_id"=>63, "name"=>"weaver_shukuchi", "localized_name"=>"Shukuchi"},
    5291 => %{"id" => 5291, "hero_id"=>63, "name"=>"weaver_geminate_attack", "localized_name"=>"Geminate Attack"},
    5292 => %{"id" => 5292, "hero_id"=>63, "name"=>"weaver_time_lapse", "localized_name"=>"Time Lapse"},
    5297 => %{"id" => 5297, "hero_id"=>64, "name"=>"jakiro_dual_breath", "localized_name"=>"Dual Breath"},
    5298 => %{"id" => 5298, "hero_id"=>64, "name"=>"jakiro_ice_path", "localized_name"=>"Ice Path"},
    5299 => %{"id" => 5299, "hero_id"=>64, "name"=>"jakiro_liquid_fire", "localized_name"=>"Liquid Fire"},
    5300 => %{"id" => 5300, "hero_id"=>64, "name"=>"jakiro_macropyre", "localized_name"=>"Macropyre"},
    5320 => %{"id" => 5320, "hero_id"=>65, "name"=>"batrider_sticky_napalm", "localized_name"=>"Sticky Napalm"},
    5321 => %{"id" => 5321, "hero_id"=>65, "name"=>"batrider_flamebreak", "localized_name"=>"Flamebreak"},
    5322 => %{"id" => 5322, "hero_id"=>65, "name"=>"batrider_firefly", "localized_name"=>"Firefly"},
    5323 => %{"id" => 5323, "hero_id"=>65, "name"=>"batrider_flaming_lasso", "localized_name"=>"Flaming Lasso"},
    5328 => %{"id" => 5328, "hero_id"=>66, "name"=>"chen_penitence", "localized_name"=>"Penitence"},
    5329 => %{"id" => 5329, "hero_id"=>66, "name"=>"chen_test_of_faith", "localized_name"=>"Test of Faith"},
    5522 => %{"id" => 5522, "hero_id"=>66, "name"=>"chen_test_of_faith_teleport", "localized_name"=>"Test of Faith"},
    5330 => %{"id" => 5330, "hero_id"=>66, "name"=>"chen_holy_persuasion", "localized_name"=>"Holy Persuasion"},
    5331 => %{"id" => 5331, "hero_id"=>66, "name"=>"chen_hand_of_god", "localized_name"=>"Hand of God"},
    5334 => %{"id" => 5334, "hero_id"=>67, "name"=>"spectre_spectral_dagger", "localized_name"=>"Spectral Dagger"},
    5335 => %{"id" => 5335, "hero_id"=>67, "name"=>"spectre_desolate", "localized_name"=>"Desolate"},
    5336 => %{"id" => 5336, "hero_id"=>67, "name"=>"spectre_dispersion", "localized_name"=>"Dispersion"},
    5337 => %{"id" => 5337, "hero_id"=>67, "name"=>"spectre_haunt", "localized_name"=>"Haunt"},
    5338 => %{"id" => 5338, "hero_id"=>67, "name"=>"spectre_reality", "localized_name"=>"Reality"},
    5339 => %{"id" => 5339, "hero_id"=>69, "name"=>"doom_bringer_devour", "localized_name"=>"Devour"},
    5340 => %{"id" => 5340, "hero_id"=>69, "name"=>"doom_bringer_scorched_earth", "localized_name"=>"Scorched Earth"},
    5341 => %{"id" => 5341, "hero_id"=>69, "name"=>"doom_bringer_lvl_death", "localized_name"=>"LVL? Death"},
    5342 => %{"id" => 5342, "hero_id"=>69, "name"=>"doom_bringer_doom", "localized_name"=>"Doom"},
    5345 => %{"id" => 5345, "hero_id"=>68, "name"=>"ancient_apparition_cold_feet", "localized_name"=>"Cold Feet"},
    5346 => %{"id" => 5346, "hero_id"=>68, "name"=>"ancient_apparition_ice_vortex", "localized_name"=>"Ice Vortex"},
    5347 => %{"id" => 5347, "hero_id"=>68, "name"=>"ancient_apparition_chilling_touch", "localized_name"=>"Chilling Touch"},
    5348 => %{"id" => 5348, "hero_id"=>68, "name"=>"ancient_apparition_ice_blast", "localized_name"=>"Ice Blast"},
    5349 => %{"id" => 5349, "hero_id"=>68, "name"=>"ancient_apparition_ice_blast_release", "localized_name"=>"Release"},
    5353 => %{"id" => 5353, "hero_id"=>71, "name"=>"spirit_breaker_charge_of_darkness", "localized_name"=>"Charge of Darkness"},
    5354 => %{"id" => 5354, "hero_id"=>71, "name"=>"spirit_breaker_empowering_haste", "localized_name"=>"Empowering Haste"},
    5355 => %{"id" => 5355, "hero_id"=>71, "name"=>"spirit_breaker_greater_bash", "localized_name"=>"Greater Bash"},
    5356 => %{"id" => 5356, "hero_id"=>71, "name"=>"spirit_breaker_nether_strike", "localized_name"=>"Nether Strike"},
    5357 => %{"id" => 5357, "hero_id"=>70, "name"=>"ursa_earthshock", "localized_name"=>"Earthshock"},
    5358 => %{"id" => 5358, "hero_id"=>70, "name"=>"ursa_overpower", "localized_name"=>"Overpower"},
    5359 => %{"id" => 5359, "hero_id"=>70, "name"=>"ursa_fury_swipes", "localized_name"=>"Fury Swipes"},
    5360 => %{"id" => 5360, "hero_id"=>70, "name"=>"ursa_enrage", "localized_name"=>"Enrage"},
    5361 => %{"id" => 5361, "hero_id"=>72, "name"=>"gyrocopter_rocket_barrage", "localized_name"=>"Rocket Barrage"},
    5362 => %{"id" => 5362, "hero_id"=>72, "name"=>"gyrocopter_homing_missile", "localized_name"=>"Homing Missile"},
    5363 => %{"id" => 5363, "hero_id"=>72, "name"=>"gyrocopter_flak_cannon", "localized_name"=>"Flak Cannon"},
    5364 => %{"id" => 5364, "hero_id"=>72, "name"=>"gyrocopter_call_down", "localized_name"=>"Call Down"},
    5365 => %{"id" => 5365, "hero_id"=>73, "name"=>"alchemist_acid_spray", "localized_name"=>"Acid Spray"},
    5366 => %{"id" => 5366, "hero_id"=>73, "name"=>"alchemist_unstable_concoction", "localized_name"=>"Unstable Concoction"},
    5367 => %{"id" => 5367, "hero_id"=>73, "name"=>"alchemist_unstable_concoction_throw", "localized_name"=>"Unstable Concoction Throw"},
    5368 => %{"id" => 5368, "hero_id"=>73, "name"=>"alchemist_goblins_greed", "localized_name"=>"Greevil's Greed"},
    5369 => %{"id" => 5369, "hero_id"=>73, "name"=>"alchemist_chemical_rage", "localized_name"=>"Chemical Rage"},
    5370 => %{"id" => 5370, "hero_id"=>74, "name"=>"invoker_quas", "localized_name"=>"Quas"},
    5371 => %{"id" => 5371, "hero_id"=>74, "name"=>"invoker_wex", "localized_name"=>"Wex"},
    5372 => %{"id" => 5372, "hero_id"=>74, "name"=>"invoker_exort", "localized_name"=>"Exort"},
    5375 => %{"id" => 5375, "hero_id"=>74, "name"=>"invoker_invoke", "localized_name"=>"Invoke"},
    5376 => %{"id" => 5376, "hero_id"=>74, "name"=>"invoker_cold_snap", "localized_name"=>"Cold Snap"},
    5381 => %{"id" => 5381, "hero_id"=>74, "name"=>"invoker_ghost_walk", "localized_name"=>"Ghost Walk"},
    5382 => %{"id" => 5382, "hero_id"=>74, "name"=>"invoker_tornado", "localized_name"=>"Tornado"},
    5383 => %{"id" => 5383, "hero_id"=>74, "name"=>"invoker_emp", "localized_name"=>"EMP"},
    5384 => %{"id" => 5384, "hero_id"=>74, "name"=>"invoker_alacrity", "localized_name"=>"Alacrity"},
    5385 => %{"id" => 5385, "hero_id"=>74, "name"=>"invoker_chaos_meteor", "localized_name"=>"Chaos Meteor"},
    5386 => %{"id" => 5386, "hero_id"=>74, "name"=>"invoker_sun_strike", "localized_name"=>"Sun Strike"},
    5387 => %{"id" => 5387, "hero_id"=>74, "name"=>"invoker_forge_spirit", "localized_name"=>"Forge Spirit"},
    5389 => %{"id" => 5389, "hero_id"=>74, "name"=>"invoker_ice_wall", "localized_name"=>"Ice Wall"},
    5390 => %{"id" => 5390, "hero_id"=>74, "name"=>"invoker_deafening_blast", "localized_name"=>"Deafening Blast"},
    5377 => %{"id" => 5377, "hero_id"=>75, "name"=>"silencer_curse_of_the_silent", "localized_name"=>"Curse of the Silent"},
    5378 => %{"id" => 5378, "hero_id"=>75, "name"=>"silencer_glaives_of_wisdom", "localized_name"=>"Glaives of Wisdom"},
    5379 => %{"id" => 5379, "hero_id"=>75, "name"=>"silencer_last_word", "localized_name"=>"Last Word"},
    5380 => %{"id" => 5380, "hero_id"=>75, "name"=>"silencer_global_silence", "localized_name"=>"Global Silence"},
    5391 => %{"id" => 5391, "hero_id"=>76, "name"=>"obsidian_destroyer_arcane_orb", "localized_name"=>"Arcane Orb"},
    5392 => %{"id" => 5392, "hero_id"=>76, "name"=>"obsidian_destroyer_astral_imprisonment", "localized_name"=>"Astral Imprisonment"},
    5393 => %{"id" => 5393, "hero_id"=>76, "name"=>"obsidian_destroyer_essence_aura", "localized_name"=>"Essence Aura"},
    5394 => %{"id" => 5394, "hero_id"=>76, "name"=>"obsidian_destroyer_sanity_eclipse", "localized_name"=>"Sanity's Eclipse"},
    5395 => %{"id" => 5395, "hero_id"=>77, "name"=>"lycan_summon_wolves", "localized_name"=>"Summon Wolves"},
    5396 => %{"id" => 5396, "hero_id"=>77, "name"=>"lycan_howl", "localized_name"=>"Howl"},
    5397 => %{"id" => 5397, "hero_id"=>77, "name"=>"lycan_feral_impulse", "localized_name"=>"Feral Impulse"},
    5398 => %{"id" => 5398, "hero_id"=>77, "name"=>"lycan_shapeshift", "localized_name"=>"Shapeshift"},
    5412 => %{"id" => 5412, "hero_id"=>80, "name"=>"lone_druid_spirit_bear", "localized_name"=>"Summon Spirit Bear"},
    5413 => %{"id" => 5413, "hero_id"=>80, "name"=>"lone_druid_rabid", "localized_name"=>"Rabid"},
    5414 => %{"id" => 5414, "hero_id"=>80, "name"=>"lone_druid_synergy", "localized_name"=>"Synergy"},
    5415 => %{"id" => 5415, "hero_id"=>80, "name"=>"lone_druid_true_form", "localized_name"=>"True Form"},
    5416 => %{"id" => 5416, "hero_id"=>80, "name"=>"lone_druid_true_form_druid", "localized_name"=>"Druid Form"},
    5417 => %{"id" => 5417, "hero_id"=>80, "name"=>"lone_druid_true_form_battle_cry", "localized_name"=>"Battle Cry"},
    5400 => %{"id" => 5400, "hero_id"=>78, "name"=>"brewmaster_thunder_clap", "localized_name"=>"Thunder Clap"},
    5401 => %{"id" => 5401, "hero_id"=>78, "name"=>"brewmaster_drunken_haze", "localized_name"=>"Drunken Haze"},
    5402 => %{"id" => 5402, "hero_id"=>78, "name"=>"brewmaster_drunken_brawler", "localized_name"=>"Drunken Brawler"},
    5403 => %{"id" => 5403, "hero_id"=>78, "name"=>"brewmaster_primal_split", "localized_name"=>"Primal Split"},
    5421 => %{"id" => 5421, "hero_id"=>79, "name"=>"shadow_demon_disruption", "localized_name"=>"Disruption"},
    5422 => %{"id" => 5422, "hero_id"=>79, "name"=>"shadow_demon_soul_catcher", "localized_name"=>"Soul Catcher"},
    5423 => %{"id" => 5423, "hero_id"=>79, "name"=>"shadow_demon_shadow_poison", "localized_name"=>"Shadow Poison"},
    5424 => %{"id" => 5424, "hero_id"=>79, "name"=>"shadow_demon_shadow_poison_release", "localized_name"=>"Shadow Poison Release"},
    5425 => %{"id" => 5425, "hero_id"=>79, "name"=>"shadow_demon_demonic_purge", "localized_name"=>"Demonic Purge"},
    5426 => %{"id" => 5426, "hero_id"=>81, "name"=>"chaos_knight_chaos_bolt", "localized_name"=>"Chaos Bolt"},
    5427 => %{"id" => 5427, "hero_id"=>81, "name"=>"chaos_knight_reality_rift", "localized_name"=>"Reality Rift"},
    5428 => %{"id" => 5428, "hero_id"=>81, "name"=>"chaos_knight_chaos_strike", "localized_name"=>"Chaos Strike"},
    5429 => %{"id" => 5429, "hero_id"=>81, "name"=>"chaos_knight_phantasm", "localized_name"=>"Phantasm"},
    5430 => %{"id" => 5430, "hero_id"=>82, "name"=>"meepo_earthbind", "localized_name"=>"Earthbind"},
    5431 => %{"id" => 5431, "hero_id"=>82, "name"=>"meepo_poof", "localized_name"=>"Poof"},
    5432 => %{"id" => 5432, "hero_id"=>82, "name"=>"meepo_geostrike", "localized_name"=>"Geostrike"},
    5433 => %{"id" => 5433, "hero_id"=>82, "name"=>"meepo_divided_we_stand", "localized_name"=>"Divided We Stand"},
    5434 => %{"id" => 5434, "hero_id"=>83, "name"=>"treant_natures_guise", "localized_name"=>"Nature's Guise"},
    5435 => %{"id" => 5435, "hero_id"=>83, "name"=>"treant_leech_seed", "localized_name"=>"Leech Seed"},
    5436 => %{"id" => 5436, "hero_id"=>83, "name"=>"treant_living_armor", "localized_name"=>"Living Armor"},
    5437 => %{"id" => 5437, "hero_id"=>83, "name"=>"treant_overgrowth", "localized_name"=>"Overgrowth"},
    5438 => %{"id" => 5438, "hero_id"=>84, "name"=>"ogre_magi_fireblast", "localized_name"=>"Fireblast"},
    5466 => %{"id" => 5466, "hero_id"=>84, "name"=>"ogre_magi_unrefined_fireblast", "localized_name"=>"Unrefined Fireblast"},
    5439 => %{"id" => 5439, "hero_id"=>84, "name"=>"ogre_magi_ignite", "localized_name"=>"Ignite"},
    5440 => %{"id" => 5440, "hero_id"=>84, "name"=>"ogre_magi_bloodlust", "localized_name"=>"Bloodlust"},
    5441 => %{"id" => 5441, "hero_id"=>84, "name"=>"ogre_magi_multicast", "localized_name"=>"Multicast"},
    5442 => %{"id" => 5442, "hero_id"=>85, "name"=>"undying_decay", "localized_name"=>"Decay"},
    5443 => %{"id" => 5443, "hero_id"=>85, "name"=>"undying_soul_rip", "localized_name"=>"Soul Rip"},
    5444 => %{"id" => 5444, "hero_id"=>85, "name"=>"undying_tombstone", "localized_name"=>"Tombstone"},
    5447 => %{"id" => 5447, "hero_id"=>85, "name"=>"undying_flesh_golem", "localized_name"=>"Flesh Golem"},
    5448 => %{"id" => 5448, "hero_id"=>86, "name"=>"rubick_telekinesis", "localized_name"=>"Telekinesis"},
    5449 => %{"id" => 5449, "hero_id"=>86, "name"=>"rubick_telekinesis_land", "localized_name"=>"Telekinesis Land"},
    5450 => %{"id" => 5450, "hero_id"=>86, "name"=>"rubick_fade_bolt", "localized_name"=>"Fade Bolt"},
    5451 => %{"id" => 5451, "hero_id"=>86, "name"=>"rubick_null_field", "localized_name"=>"Null Field"},
    5452 => %{"id" => 5452, "hero_id"=>86, "name"=>"rubick_spell_steal", "localized_name"=>"Spell Steal"},
    5458 => %{"id" => 5458, "hero_id"=>87, "name"=>"disruptor_thunder_strike", "localized_name"=>"Thunder Strike"},
    5459 => %{"id" => 5459, "hero_id"=>87, "name"=>"disruptor_glimpse", "localized_name"=>"Glimpse"},
    5460 => %{"id" => 5460, "hero_id"=>87, "name"=>"disruptor_kinetic_field", "localized_name"=>"Kinetic Field"},
    5461 => %{"id" => 5461, "hero_id"=>87, "name"=>"disruptor_static_storm", "localized_name"=>"Static Storm"},
    5462 => %{"id" => 5462, "hero_id"=>88, "name"=>"nyx_assassin_impale", "localized_name"=>"Impale"},
    5463 => %{"id" => 5463, "hero_id"=>88, "name"=>"nyx_assassin_mana_burn", "localized_name"=>"Mana Burn"},
    5464 => %{"id" => 5464, "hero_id"=>88, "name"=>"nyx_assassin_spiked_carapace", "localized_name"=>"Spiked Carapace"},
    5465 => %{"id" => 5465, "hero_id"=>88, "name"=>"nyx_assassin_vendetta", "localized_name"=>"Vendetta"},
    5467 => %{"id" => 5467, "hero_id"=>89, "name"=>"naga_siren_mirror_image", "localized_name"=>"Mirror Image"},
    5468 => %{"id" => 5468, "hero_id"=>89, "name"=>"naga_siren_ensnare", "localized_name"=>"Ensnare"},
    5469 => %{"id" => 5469, "hero_id"=>89, "name"=>"naga_siren_rip_tide", "localized_name"=>"Rip Tide"},
    5470 => %{"id" => 5470, "hero_id"=>89, "name"=>"naga_siren_song_of_the_siren", "localized_name"=>"Song of the Siren"},
    5478 => %{"id" => 5478, "hero_id"=>89, "name"=>"naga_siren_song_of_the_siren_cancel", "localized_name"=>"Song of the Siren Cancel"},
    5471 => %{"id" => 5471, "hero_id"=>90, "name"=>"keeper_of_the_light_illuminate", "localized_name"=>"Illuminate"},
    5472 => %{"id" => 5472, "hero_id"=>90, "name"=>"keeper_of_the_light_mana_leak", "localized_name"=>"Mana Leak"},
    5473 => %{"id" => 5473, "hero_id"=>90, "name"=>"keeper_of_the_light_chakra_magic", "localized_name"=>"Chakra Magic"},
    5474 => %{"id" => 5474, "hero_id"=>90, "name"=>"keeper_of_the_light_spirit_form", "localized_name"=>"Spirit Form"},
    5475 => %{"id" => 5475, "hero_id"=>90, "name"=>"keeper_of_the_light_recall", "localized_name"=>"Recall"},
    5476 => %{"id" => 5476, "hero_id"=>90, "name"=>"keeper_of_the_light_blinding_light", "localized_name"=>"Blinding Light"},
    5477 => %{"id" => 5477, "hero_id"=>90, "name"=>"keeper_of_the_light_illuminate_end", "localized_name"=>"Release Illuminate"},
    5479 => %{"id" => 5479, "hero_id"=>90, "name"=>"keeper_of_the_light_spirit_form_illuminate", "localized_name"=>"Illuminate"},
    5503 => %{"id" => 5503, "hero_id"=>90, "name"=>"keeper_of_the_light_spirit_form_illuminate_end", "localized_name"=>"Release Illuminate"},
    5480 => %{"id" => 5480, "hero_id"=>92, "name"=>"visage_grave_chill", "localized_name"=>"Grave Chill"},
    5481 => %{"id" => 5481, "hero_id"=>92, "name"=>"visage_soul_assumption", "localized_name"=>"Soul Assumption"},
    5482 => %{"id" => 5482, "hero_id"=>92, "name"=>"visage_gravekeepers_cloak", "localized_name"=>"Gravekeeper's Cloak"},
    5483 => %{"id" => 5483, "hero_id"=>92, "name"=>"visage_summon_familiars", "localized_name"=>"Summon Familiars"},
    5485 => %{"id" => 5485, "hero_id"=>91, "name"=>"wisp_tether", "localized_name"=>"Tether"},
    5486 => %{"id" => 5486, "hero_id"=>91, "name"=>"wisp_spirits", "localized_name"=>"Spirits"},
    5487 => %{"id" => 5487, "hero_id"=>91, "name"=>"wisp_overcharge", "localized_name"=>"Overcharge"},
    5488 => %{"id" => 5488, "hero_id"=>91, "name"=>"wisp_relocate", "localized_name"=>"Relocate"},
    5489 => %{"id" => 5489, "hero_id"=>91, "name"=>"wisp_tether_break", "localized_name"=>"Break Tether"},
    5490 => %{"id" => 5490, "hero_id"=>91, "name"=>"wisp_spirits_in", "localized_name"=>"Spirits In"},
    5493 => %{"id" => 5493, "hero_id"=>91, "name"=>"wisp_spirits_out", "localized_name"=>"Spirits Out"},
    5494 => %{"id" => 5494, "hero_id"=>93, "name"=>"slark_dark_pact", "localized_name"=>"Dark Pact"},
    5495 => %{"id" => 5495, "hero_id"=>93, "name"=>"slark_pounce", "localized_name"=>"Pounce"},
    5496 => %{"id" => 5496, "hero_id"=>93, "name"=>"slark_essence_shift", "localized_name"=>"Essence Shift"},
    5497 => %{"id" => 5497, "hero_id"=>93, "name"=>"slark_shadow_dance", "localized_name"=>"Shadow Dance"},
    5504 => %{"id" => 5504, "hero_id"=>94, "name"=>"medusa_split_shot", "localized_name"=>"Split Shot"},
    5505 => %{"id" => 5505, "hero_id"=>94, "name"=>"medusa_mystic_snake", "localized_name"=>"Mystic Snake"},
    5506 => %{"id" => 5506, "hero_id"=>94, "name"=>"medusa_mana_shield", "localized_name"=>"Mana Shield"},
    5507 => %{"id" => 5507, "hero_id"=>94, "name"=>"medusa_stone_gaze", "localized_name"=>"Stone Gaze"},
    5508 => %{"id" => 5508, "hero_id"=>95, "name"=>"troll_warlord_berserkers_rage", "localized_name"=>"Berserker's Rage"},
    5509 => %{"id" => 5509, "hero_id"=>95, "name"=>"troll_warlord_whirling_axes_ranged", "localized_name"=>"Whirling Axes (Ranged)"},
    5510 => %{"id" => 5510, "hero_id"=>95, "name"=>"troll_warlord_whirling_axes_melee", "localized_name"=>"Whirling Axes (Melee)"},
    5511 => %{"id" => 5511, "hero_id"=>95, "name"=>"troll_warlord_fervor", "localized_name"=>"Fervor"},
    5512 => %{"id" => 5512, "hero_id"=>95, "name"=>"troll_warlord_battle_trance", "localized_name"=>"Battle Trance"},
    5514 => %{"id" => 5514, "hero_id"=>96, "name"=>"centaur_hoof_stomp", "localized_name"=>"Hoof Stomp"},
    5515 => %{"id" => 5515, "hero_id"=>96, "name"=>"centaur_double_edge", "localized_name"=>"Double Edge"},
    5516 => %{"id" => 5516, "hero_id"=>96, "name"=>"centaur_return", "localized_name"=>"Return"},
    5517 => %{"id" => 5517, "hero_id"=>96, "name"=>"centaur_stampede", "localized_name"=>"Stampede"},
    5518 => %{"id" => 5518, "hero_id"=>97, "name"=>"magnataur_shockwave", "localized_name"=>"Shockwave"},
    5519 => %{"id" => 5519, "hero_id"=>97, "name"=>"magnataur_empower", "localized_name"=>"Empower"},
    5520 => %{"id" => 5520, "hero_id"=>97, "name"=>"magnataur_skewer", "localized_name"=>"Skewer"},
    5521 => %{"id" => 5521, "hero_id"=>97, "name"=>"magnataur_reverse_polarity", "localized_name"=>"Reverse Polarity"},
    5524 => %{"id" => 5524, "hero_id"=>98, "name"=>"shredder_whirling_death", "localized_name"=>"Whirling Death"},
    5525 => %{"id" => 5525, "hero_id"=>98, "name"=>"shredder_timber_chain", "localized_name"=>"Timber Chain"},
    5526 => %{"id" => 5526, "hero_id"=>98, "name"=>"shredder_reactive_armor", "localized_name"=>"Reactive Armor"},
    5527 => %{"id" => 5527, "hero_id"=>98, "name"=>"shredder_chakram", "localized_name"=>"Chakram"},
    5528 => %{"id" => 5528, "hero_id"=>98, "name"=>"shredder_return_chakram", "localized_name"=>"Return Chakram"},
    5548 => %{"id" => 5548, "hero_id"=>99, "name"=>"bristleback_viscous_nasal_goo", "localized_name"=>"Viscous Nasal Goo"},
    5549 => %{"id" => 5549, "hero_id"=>99, "name"=>"bristleback_quill_spray", "localized_name"=>"Quill Spray"},
    5550 => %{"id" => 5550, "hero_id"=>99, "name"=>"bristleback_bristleback", "localized_name"=>"Bristleback"},
    5551 => %{"id" => 5551, "hero_id"=>99, "name"=>"bristleback_warpath", "localized_name"=>"Warpath"},
    5565 => %{"id" => 5565, "hero_id"=>100, "name"=>"tusk_ice_shards", "localized_name"=>"Ice Shards"},
    5566 => %{"id" => 5566, "hero_id"=>100, "name"=>"tusk_snowball", "localized_name"=>"Snowball"},
    5567 => %{"id" => 5567, "hero_id"=>100, "name"=>"tusk_frozen_sigil", "localized_name"=>"Frozen Sigil"},
    5568 => %{"id" => 5568, "hero_id"=>100, "name"=>"tusk_walrus_punch", "localized_name"=>"Walrus PUNCH!"},
    5581 => %{"id" => 5581, "hero_id"=>101, "name"=>"skywrath_mage_arcane_bolt", "localized_name"=>"Arcane Bolt"},
    5582 => %{"id" => 5582, "hero_id"=>101, "name"=>"skywrath_mage_concussive_shot", "localized_name"=>"Concussive Shot"},
    5583 => %{"id" => 5583, "hero_id"=>101, "name"=>"skywrath_mage_ancient_seal", "localized_name"=>"Ancient Seal"},
    5584 => %{"id" => 5584, "hero_id"=>101, "name"=>"skywrath_mage_mystic_flare", "localized_name"=>"Mystic Flare"},
    5585 => %{"id" => 5585, "hero_id"=>102, "name"=>"abaddon_death_coil", "localized_name"=>"Mist Coil"},
    5586 => %{"id" => 5586, "hero_id"=>102, "name"=>"abaddon_aphotic_shield", "localized_name"=>"Aphotic Shield"},
    5587 => %{"id" => 5587, "hero_id"=>102, "name"=>"abaddon_frostmourne", "localized_name"=>"Curse of Avernus"},
    5588 => %{"id" => 5588, "hero_id"=>102, "name"=>"abaddon_borrowed_time", "localized_name"=>"Borrowed Time"},
    5589 => %{"id" => 5589, "hero_id"=>103, "name"=>"elder_titan_echo_stomp", "localized_name"=>"Echo Stomp"},
    5591 => %{"id" => 5591, "hero_id"=>103, "name"=>"elder_titan_ancestral_spirit", "localized_name"=>"Astral Spirit"},
    5592 => %{"id" => 5592, "hero_id"=>103, "name"=>"elder_titan_return_spirit", "localized_name"=>"Return Astral Spirit"},
    5593 => %{"id" => 5593, "hero_id"=>103, "name"=>"elder_titan_natural_order", "localized_name"=>"Natural Order"},
    5594 => %{"id" => 5594, "hero_id"=>103, "name"=>"elder_titan_earth_splitter", "localized_name"=>"Earth Splitter"},
    5595 => %{"id" => 5595, "hero_id"=>104, "name"=>"legion_commander_overwhelming_odds", "localized_name"=>"Overwhelming Odds"},
    5596 => %{"id" => 5596, "hero_id"=>104, "name"=>"legion_commander_press_the_attack", "localized_name"=>"Press The Attack"},
    5597 => %{"id" => 5597, "hero_id"=>104, "name"=>"legion_commander_moment_of_courage", "localized_name"=>"Moment of Courage"},
    5598 => %{"id" => 5598, "hero_id"=>104, "name"=>"legion_commander_duel", "localized_name"=>"Duel"},
    5603 => %{"id" => 5603, "hero_id"=>106, "name"=>"ember_spirit_searing_chains", "localized_name"=>"Searing Chains"},
    5604 => %{"id" => 5604, "hero_id"=>106, "name"=>"ember_spirit_sleight_of_fist", "localized_name"=>"Sleight of Fist"},
    5605 => %{"id" => 5605, "hero_id"=>106, "name"=>"ember_spirit_flame_guard", "localized_name"=>"Flame Guard"},
    5606 => %{"id" => 5606, "hero_id"=>106, "name"=>"ember_spirit_fire_remnant", "localized_name"=>"Fire Remnant"},
    5607 => %{"id" => 5607, "hero_id"=>106, "name"=>"ember_spirit_activate_fire_remnant", "localized_name"=>"Activate Fire Remnant"},
    5608 => %{"id" => 5608, "hero_id"=>107, "name"=>"earth_spirit_boulder_smash", "localized_name"=>"Boulder Smash"},
    5609 => %{"id" => 5609, "hero_id"=>107, "name"=>"earth_spirit_rolling_boulder", "localized_name"=>"Rolling Boulder"},
    5610 => %{"id" => 5610, "hero_id"=>107, "name"=>"earth_spirit_geomagnetic_grip", "localized_name"=>"Geomagnetic Grip"},
    5611 => %{"id" => 5611, "hero_id"=>107, "name"=>"earth_spirit_stone_caller", "localized_name"=>"Stone Remnant"},
    5612 => %{"id" => 5612, "hero_id"=>107, "name"=>"earth_spirit_magnetize", "localized_name"=>"Magnetize"},
    5619 => %{"id" => 5619, "hero_id"=>109, "name"=>"terrorblade_reflection", "localized_name"=>"Reflection"},
    5620 => %{"id" => 5620, "hero_id"=>109, "name"=>"terrorblade_conjure_image", "localized_name"=>"Conjure Image"},
    5621 => %{"id" => 5621, "hero_id"=>109, "name"=>"terrorblade_metamorphosis", "localized_name"=>"Metamorphosis"},
    5622 => %{"id" => 5622, "hero_id"=>109, "name"=>"terrorblade_sunder", "localized_name"=>"Sunder"},
    5623 => %{"id" => 5623, "hero_id"=>110, "name"=>"phoenix_icarus_dive", "localized_name"=>"Icarus Dive"},
    5624 => %{"id" => 5624, "hero_id"=>110, "name"=>"phoenix_icarus_dive_stop", "localized_name"=>"Stop Icarus Dive"},
    5625 => %{"id" => 5625, "hero_id"=>110, "name"=>"phoenix_fire_spirits", "localized_name"=>"Fire Spirits"},
    5626 => %{"id" => 5626, "hero_id"=>110, "name"=>"phoenix_sun_ray", "localized_name"=>"Sun Ray"},
    5627 => %{"id" => 5627, "hero_id"=>110, "name"=>"phoenix_sun_ray_stop", "localized_name"=>"Stop Sun Ray"},
    5628 => %{"id" => 5628, "hero_id"=>110, "name"=>"phoenix_sun_ray_toggle_move", "localized_name"=>"Toggle Movement"},
    5629 => %{"id" => 5629, "hero_id"=>110, "name"=>"phoenix_sun_ray_toggle_move_empty", "localized_name"=>""},
    5630 => %{"id" => 5630, "hero_id"=>110, "name"=>"phoenix_supernova", "localized_name"=>"Supernova"},
    5631 => %{"id" => 5631, "hero_id"=>110, "name"=>"phoenix_launch_fire_spirit", "localized_name"=>"Launch Fire Spirit"}
  }

  def get(id), do: @abilities[id]

  def localized_name(id), do: @abilities[id]["localized_name"]

  def name(id), do: @abilities[id]["name"]

  def for_hero(hero_id) when is_integer(hero_id) do
    Map.values(@abilities)
      |> Enum.filter fn(x) -> x["hero_id"] == hero_id end
  end

  def all, do: @abilities
end
